name: Build React on S3
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master # リポジトリをチェックアウト

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build # React ビルド
              env:
                  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }} # React env

            - name: Deploy # S3にデプロイ
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws s3 cp --recursive --region ap-northeast-1 build s3://${{ secrets.S3_BUCKET_NAME }}

            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
                  PATHS: '/index.html'
                  AWS_REGION: 'us-east-1'
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
